blueprint:
  name: "Smart HVAC Control with Energy Price & Solar"
  description: "Control HVAC based on temperature, electricity price and solar energy surplus"
  domain: automation
  author: "Madd0x"
  source: "https://github.com/madd0x2000/home-assistant-blueprints"
  version: "1.0.0"
  input:
    # Sensorer
    temperature_sensor:
      name: "Temperatursensor"
      selector:
        entity:
          domain: sensor
          device_class: temperature
          
    hvac_entity:
      name: "HVAC-enhet"
      selector:
        entity:
          domain: climate
          
    energy_sensor:
      name: "Solenergiöverskott/underskott sensor"
      description: "Sensor som visar +W vid överskott, -W vid underskott"
      selector:
        entity:
          domain: sensor
          
    price_sensor:
      name: "Elprissensor"
      description: "Sensor med current_price attribut för aktuellt timpris"
      selector:
        entity:
          domain: sensor

    # Temperaturinställningar
    target_temp_high:
      name: "Måltemperatur vid bra förhållanden"
      default: 21
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"
          
    target_temp_low:
      name: "Måltemperatur vid dåliga förhållanden"
      default: 19
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"

    # Tröskelvärden
    energy_threshold:
      name: "Solenergitröskel (W)"
      description: "Minimi överskott för att aktivera högre temperatur"
      default: 500
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "W"
          
    price_threshold:
      name: "Elpriströskel (öre/kWh)"
      description: "Max elpris för att anses vara lågt pris"
      default: 50
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: "öre/kWh"

    # Fläktinställningar
    normal_fan_mode:
      name: "Normalt fläktläge"
      default: "auto"
      selector:
        select:
          options:
            - label: "Auto"
              value: "auto"
            - label: "Låg"
              value: "1"
            - label: "Mellan"
              value: "3"
            - label: "Hög"
              value: "5"

    boost_fan_mode:
      name: "Boost fläktläge vid kallt"
      description: "Fläktläge när temperaturen är 2+ grader under måltemp"
      default: "4"
      selector:
        select:
          options:
            - label: "Hög"
              value: "5"
            - label: "Mycket hög"
              value: "4"
            - label: "Max"
              value: "3"

    temp_difference:
      name: "Temperaturdifferens för aktivering"
      default: 1.0
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.5
          unit_of_measurement: "°C"

    boost_temp_difference:
      name: "Temperaturdifferens för boost-läge"
      description: "Vid hur många grader under måltemp som boost ska aktiveras"
      default: 2.0
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5
          unit_of_measurement: "°C"

variables:
  current_temp: "{{ states(temperature_sensor) | float }}"
  energy_balance: "{{ states(energy_sensor) | float(0) }}"
  electricity_price: "{{ state_attr(price_sensor, 'current_price') | float(100) }}"
  hvac_state: "{{ states(hvac_entity) }}"
  hvac_mode: "{{ state_attr(hvac_entity, 'hvac_mode') }}"

trigger:
  - platform: state
    entity_id: !input temperature_sensor
  - platform: state
    entity_id: !input price_sensor
  - platform: state
    entity_id: !input energy_sensor
  - platform: time_pattern
    minutes: "/10"

action:
  - variables:
      # Beräkna optimal temperatur baserat på förhållanden
      has_solar_excess: "{{ energy_balance > energy_threshold }}"
      is_low_price: "{{ electricity_price < price_threshold }}"
      
      target_temperature: >
        {% if has_solar_excess and is_low_price %}
          {{ target_temp_high }}
        {% elif has_solar_excess or is_low_price %}
          {{ (target_temp_high + target_temp_low) / 2 }}
        {% else %}
          {{ target_temp_low }}
        {% endif %}

      # Beräkna temperaturdifferens
      temp_diff: "{{ target_temperature - current_temp }}"
      
      # Bestäm om värmen behövs
      needs_heating: "{{ current_temp < (target_temperature - temp_difference) }}"
      
      # Bestäm om boost-läge behövs (2+ grader under måltemp)
      needs_boost: "{{ temp_diff >= boost_temp_difference }}"
      
      # Välj fläktläge baserat på behov
      selected_fan_mode: >
        {% if needs_boost %}
          {{ boost_fan_mode }}
        {% else %}
          {{ normal_fan_mode }}
        {% endif %}

      current_mode: "{{ state_attr(hvac_entity, 'hvac_mode') }}"

  # HVAC-styrning
  - choose:
      - conditions:
          - "{{ needs_heating }}"
          - "{{ hvac_state == 'off' or current_mode != 'heat' }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input hvac_entity
          - delay: "00:00:02"
          - service: climate.set_hvac_mode
            target:
              entity_id: !input hvac_entity
            data:
              hvac_mode: heat
          - delay: "00:00:03"

      - conditions:
          - "{{ not needs_heating }}"
          - "{{ current_mode == 'heat' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input hvac_entity
            data:
              hvac_mode: off

  # Uppdatera inställningar om värmen är på
  - conditions:
      - "{{ needs_heating }}"
      - "{{ current_mode == 'heat' }}"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: !input hvac_entity
        data:
          temperature: "{{ target_temperature }}"

      - service: climate.set_fan_mode
        target:
          entity_id: !input hvac_entity
        data:
          fan_mode: "{{ selected_fan_mode }}"

  # Förbättrad loggning med fläktinfo
  - service: system_log.write
    data:
      level: info
      message: >
        Värmestyrning: 
        Rumstemp={{ current_temp }}°C, 
        Måltemp={{ target_temperature }}°C,
        TempDiff={{ temp_diff }}°C,
        Energibalans={{ energy_balance }}W,
        Elpris={{ electricity_price }}öre,
        Överskott={{ has_solar_excess }},
        LågtPris={{ is_low_price }},
        BehöverVärme={{ needs_heating }},
        BoostLäge={{ needs_boost }},
        Fläktläge={{ selected_fan_mode }}

mode: queued
max: 5
