blueprint:
  name: "Multi-Zone HVAC Control with Energy Price & Solar"
  description: "Control multiple HVAC zones based on temperature, electricity price, solar production and heat pump consumption"
  domain: automation
  input:
    # Global Sensors
    solar_production_sensor:
      name: "Solar Production Sensor"
      selector:
        entity:
          domain: sensor
          
    net_consumption_sensor:
      name: "Net Consumption Sensor" 
      selector:
        entity:
          domain: sensor
          
    price_sensor:
      name: "Electricity Price Sensor"
      selector:
        entity:
          domain: sensor

    # Zone 1 Configuration
    zone1_temperature_sensor:
      name: "Zone 1 - Temperature Sensor"
      selector:
        entity:
          domain: sensor
          device_class: temperature
          
    zone1_hvac_entity:
      name: "Zone 1 - HVAC Entity"
      selector:
        entity:
          domain: climate
          
    zone1_heatpump_consumption_sensor:
      name: "Zone 1 - Heat Pump Consumption Sensor"
      selector:
        entity:
          domain: sensor

    zone1_target_temp_high:
      name: "Zone 1 - Target Temperature at Good Conditions"
      default: 22
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"
          
    zone1_target_temp_low:
      name: "Zone 1 - Target Temperature at Poor Conditions"
      default: 20
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"

    # Zone 2 Configuration
    zone2_temperature_sensor:
      name: "Zone 2 - Temperature Sensor"
      selector:
        entity:
          domain: sensor
          device_class: temperature
          
    zone2_hvac_entity:
      name: "Zone 2 - HVAC Entity"
      selector:
        entity:
          domain: climate
          
    zone2_heatpump_consumption_sensor:
      name: "Zone 2 - Heat Pump Consumption Sensor"
      selector:
        entity:
          domain: sensor

    zone2_target_temp_high:
      name: "Zone 2 - Target Temperature at Good Conditions"
      default: 22
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"
          
    zone2_target_temp_low:
      name: "Zone 2 - Target Temperature at Poor Conditions"
      default: 20
      selector:
        number:
          min: 10
          max: 31
          step: 0.5
          unit_of_measurement: "°C"

    # Night Mode Settings
    night_mode_start:
      name: "Night Mode Start Time"
      default: "00:00:00"
      selector:
        time: {}

    night_mode_end:
      name: "Night Mode End Time"
      default: "05:00:00"
      selector:
        time: {}

    zone1_night_temperature:
      name: "Zone 1 - Night Temperature"
      default: 18
      selector:
        number:
          min: 10
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

    zone2_night_temperature:
      name: "Zone 2 - Night Temperature"
      default: 18
      selector:
        number:
          min: 10
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

    # Global Settings
    base_consumption:
      name: "Base Household Consumption (W)"
      default: 400
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: "W"

    temperature_boost:
      name: "Temperature Boost for Heating (°C)"
      default: 1.0
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.5
          unit_of_measurement: "°C"

    # Global Thresholds
    solar_threshold:
      name: "Solar Production Threshold (W)"
      default: 300
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: "W"
          
    export_threshold:
      name: "Energy Export Threshold (W)"
      default: -500
      selector:
        number:
          min: -5000
          max: 0
          unit_of_measurement: "W"
          
    price_threshold:
      name: "Electricity Price Threshold (öre/kWh)"
      default: 50
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: "öre/kWh"

    heatpump_threshold:
      name: "Heat Pump Consumption Threshold (W)"
      default: 800
      selector:
        number:
          min: 0
          max: 3000
          unit_of_measurement: "W"

    # Fan Settings
    normal_fan_mode:
      name: "Normal Fan Mode"
      default: "auto"
      selector:
        select:
          options:
            - label: "Auto"
              value: "auto"
            - label: "1 - Very Low"
              value: "1"
            - label: "2 - Low"
              value: "2"
            - label: "3 - Medium"
              value: "3"
            - label: "4 - High"
              value: "4"
            - label: "5 - Very High"
              value: "5"

    boost_fan_mode:
      name: "Boost Fan Mode when Cold"
      default: "4"
      selector:
        select:
          options:
            - label: "3 - Medium"
              value: "3"
            - label: "4 - High"
              value: "4"
            - label: "5 - Very High"
              value: "5"

    temp_difference:
      name: "Temperature Difference for Activation"
      default: 1.0
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.5
          unit_of_measurement: "°C"

    boost_temp_difference:
      name: "Temperature Difference for Boost Mode"
      default: 2.0
      selector:
        number:
          min: 1.0
          max: 5.0
          step: 0.5
          unit_of_measurement: "°C"

# ✅ ANVÄND VARIABLES PÅ ROTNIVÅ FÖR INPUT-VÄRDEN
variables:
  base_consumption_val: !input base_consumption
  temperature_boost_val: !input temperature_boost
  solar_threshold_val: !input solar_threshold
  export_threshold_val: !input export_threshold
  price_threshold_val: !input price_threshold
  heatpump_threshold_val: !input heatpump_threshold
  temp_difference_val: !input temp_difference
  boost_temp_difference_val: !input boost_temp_difference
  zone1_target_temp_high_val: !input zone1_target_temp_high
  zone1_target_temp_low_val: !input zone1_target_temp_low
  zone2_target_temp_high_val: !input zone2_target_temp_high
  zone2_target_temp_low_val: !input zone2_target_temp_low
  zone1_night_temperature_val: !input zone1_night_temperature
  zone2_night_temperature_val: !input zone2_night_temperature
  normal_fan_mode_val: !input normal_fan_mode
  boost_fan_mode_val: !input boost_fan_mode

trigger:
  - platform: state
    entity_id: !input price_sensor
  - platform: state
    entity_id: !input solar_production_sensor
  - platform: state
    entity_id: !input net_consumption_sensor
  - platform: state
    entity_id: !input zone1_temperature_sensor
  - platform: state
    entity_id: !input zone1_heatpump_consumption_sensor
  - platform: state
    entity_id: !input zone2_temperature_sensor
  - platform: state
    entity_id: !input zone2_heatpump_consumption_sensor
  - platform: time
    at: !input night_mode_start
  - platform: time
    at: !input night_mode_end
  - platform: time_pattern
    minutes: "/10"

action:
  - variables:
      # ✅ ANVÄND !input DIRECT FÖR SENSOR-ENTITIES
      solar_production: >
        {% set sensor = '!input solar_production_sensor' %}
        {% if states(sensor) != 'unknown' and states(sensor) != 'unavailable' %}
          {{ states(sensor) | float(0) }}
        {% else %}
          0
        {% endif %}
      
      net_consumption: >
        {% set sensor = '!input net_consumption_sensor' %}
        {% if states(sensor) != 'unknown' and states(sensor) != 'unavailable' %}
          {{ states(sensor) | float(0) }}
        {% else %}
          0
        {% endif %}
      
      electricity_price: >
        {% set sensor = '!input price_sensor' %}
        {% if states(sensor) != 'unknown' and states(sensor) != 'unavailable' %}
          {{ state_attr(sensor, 'current_price') | float(100) }}
        {% else %}
          100
        {% endif %}
      
      is_night_mode: >
        {% set now = now().strftime('%H:%M:%S') %}
        {% set start = '!input night_mode_start' %}
        {% set end = '!input night_mode_end' %}
        {{ (now >= start and now <= end) or (start > end and (now >= start or now <= end)) }}

      has_solar_production: "{{ solar_production > solar_threshold_val }}"
      available_solar: "{{ solar_production - base_consumption_val }}"
      has_real_excess: "{{ available_solar > 0 }}"
      has_export_excess: "{{ net_consumption < export_threshold_val }}"
      is_low_price: "{{ electricity_price < price_threshold_val }}"
      
      # ✅ ANVÄND !input DIRECT FÖR ZONE SENSORER
      zone1_current_temp: >
        {% set sensor = '!input zone1_temperature_sensor' %}
        {{ states(sensor) | float }}
      
      zone1_heatpump_consumption: >
        {% set sensor = '!input zone1_heatpump_consumption_sensor' %}
        {{ states(sensor) | float(0) }}
      
      zone1_is_low_consumption: "{{ zone1_heatpump_consumption <= heatpump_threshold_val }}"
      
      # ✅ SMART LOGIK - SOLÖVERSKOTT SLÅR ELPRIS
      zone1_base_target: >
        {% if is_night_mode %}
          {{ zone1_night_temperature_val }}
        {% else %}
          {% if has_real_excess %}
            {{ zone1_target_temp_high_val }}  # ✅ ALLTID hög temp när solöverskott finns
          {% elif has_solar_production and zone1_is_low_consumption %}
            {% if is_low_price %}
              {{ (zone1_target_temp_high_val + zone1_target_temp_low_val) / 2 }}
            {% else %}
              {{ zone1_target_temp_low_val }}
            {% endif %}
          {% elif is_low_price and zone1_is_low_consumption %}
            {{ (zone1_target_temp_high_val + zone1_target_temp_low_val) / 2 }}
          {% else %}
            {{ zone1_target_temp_low_val }}
          {% endif %}
        {% endif %}
      
      zone1_final_target: "{{ zone1_base_target + temperature_boost_val }}"
      zone1_limited_target: >
        {% if zone1_final_target > 31 %}
          31
        {% elif zone1_final_target < 10 %}
          10
        {% else %}
          {{ zone1_final_target }}
        {% endif %}
      
      zone1_temp_diff: "{{ zone1_base_target - zone1_current_temp }}"
      zone1_needs_heating: "{{ zone1_current_temp < (zone1_base_target - temp_difference_val) }}"
      zone1_needs_boost: "{{ zone1_temp_diff >= boost_temp_difference_val }}"
      zone1_selected_fan_mode: "{{ boost_fan_mode_val if zone1_needs_boost else normal_fan_mode_val }}"
      
      zone1_current_mode: >
        {% set entity = '!input zone1_hvac_entity' %}
        {{ state_attr(entity, 'hvac_mode') }}

      # ✅ SAMMA FÖR ZONE 2
      zone2_current_temp: >
        {% set sensor = '!input zone2_temperature_sensor' %}
        {{ states(sensor) | float }}
      
      zone2_heatpump_consumption: >
        {% set sensor = '!input zone2_heatpump_consumption_sensor' %}
        {{ states(sensor) | float(0) }}
      
      zone2_is_low_consumption: "{{ zone2_heatpump_consumption <= heatpump_threshold_val }}"
      
      zone2_base_target: >
        {% if is_night_mode %}
          {{ zone2_night_temperature_val }}
        {% else %}
          {% if has_real_excess %}
            {{ zone2_target_temp_high_val }}  # ✅ ALLTID hög temp när solöverskott finns
          {% elif has_solar_production and zone2_is_low_consumption %}
            {% if is_low_price %}
              {{ (zone2_target_temp_high_val + zone2_target_temp_low_val) / 2 }}
            {% else %}
              {{ zone2_target_temp_low_val }}
            {% endif %}
          {% elif is_low_price and zone2_is_low_consumption %}
            {{ (zone2_target_temp_high_val + zone2_target_temp_low_val) / 2 }}
          {% else %}
            {{ zone2_target_temp_low_val }}
          {% endif %}
        {% endif %}
      
      zone2_final_target: "{{ zone2_base_target + temperature_boost_val }}"
      zone2_limited_target: >
        {% if zone2_final_target > 31 %}
          31
        {% elif zone2_final_target < 10 %}
          10
        {% else %}
          {{ zone2_final_target }}
        {% endif %}
      
      zone2_temp_diff: "{{ zone2_base_target - zone2_current_temp }}"
      zone2_needs_heating: "{{ zone2_current_temp < (zone2_base_target - temp_difference_val) }}"
      zone2_needs_boost: "{{ zone2_temp_diff >= boost_temp_difference_val }}"
      zone2_selected_fan_mode: "{{ boost_fan_mode_val if zone2_needs_boost else normal_fan_mode_val }}"
      
      zone2_current_mode: >
        {% set entity = '!input zone2_hvac_entity' %}
        {{ state_attr(entity, 'hvac_mode') }}

  # Zone 1 Control
  - choose:
      - conditions:
          - "{{ zone1_needs_heating }}"
          - "{{ states('!input zone1_hvac_entity') == 'off' or zone1_current_mode != 'heat' }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input zone1_hvac_entity
          - delay: "00:00:02"
          - service: climate.set_hvac_mode
            target:
              entity_id: !input zone1_hvac_entity
            data:
              hvac_mode: heat
          - delay: "00:00:03"
          - service: climate.set_temperature
            target:
              entity_id: !input zone1_hvac_entity
            data:
              temperature: "{{ zone1_limited_target }}"
          - service: climate.set_fan_mode
            target:
              entity_id: !input zone1_hvac_entity
            data:
              fan_mode: "{{ zone1_selected_fan_mode }}"
      - conditions:
          - "{{ not zone1_needs_heating }}"
          - "{{ zone1_current_mode == 'heat' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input zone1_hvac_entity
            data:
              hvac_mode: off
      - conditions:
          - "{{ zone1_needs_heating }}"
          - "{{ zone1_current_mode == 'heat' }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input zone1_hvac_entity
            data:
              temperature: "{{ zone1_limited_target }}"
          - service: climate.set_fan_mode
            target:
              entity_id: !input zone1_hvac_entity
            data:
              fan_mode: "{{ zone1_selected_fan_mode }}"

  # Zone 2 Control
  - choose:
      - conditions:
          - "{{ zone2_needs_heating }}"
          - "{{ states('!input zone2_hvac_entity') == 'off' or zone2_current_mode != 'heat' }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: !input zone2_hvac_entity
          - delay: "00:00:02"
          - service: climate.set_hvac_mode
            target:
              entity_id: !input zone2_hvac_entity
            data:
              hvac_mode: heat
          - delay: "00:00:03"
          - service: climate.set_temperature
            target:
              entity_id: !input zone2_hvac_entity
            data:
              temperature: "{{ zone2_limited_target }}"
          - service: climate.set_fan_mode
            target:
              entity_id: !input zone2_hvac_entity
            data:
              fan_mode: "{{ zone2_selected_fan_mode }}"
      - conditions:
          - "{{ not zone2_needs_heating }}"
          - "{{ zone2_current_mode == 'heat' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input zone2_hvac_entity
            data:
              hvac_mode: off
      - conditions:
          - "{{ zone2_needs_heating }}"
          - "{{ zone2_current_mode == 'heat' }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input zone2_hvac_entity
            data:
              temperature: "{{ zone2_limited_target }}"
          - service: climate.set_fan_mode
            target:
              entity_id: !input zone2_hvac_entity
            data:
              fan_mode: "{{ zone2_selected_fan_mode }}"

  # Logging
  - service: system_log.write
    data:
      level: info
      message: >
        Multi-Zone HVAC Control:
        Global - Solar={{ solar_production }}W, AvailableSolar={{ available_solar }}W, Price={{ electricity_price }}öre, RealExcess={{ has_real_excess }}, Export={{ has_export_excess }}, NightMode={{ is_night_mode }}
        Zone1 - Temp={{ zone1_current_temp }}°C, Target={{ zone1_limited_target }}°C, Heating={{ zone1_needs_heating }}
        Zone2 - Temp={{ zone2_current_temp }}°C, Target={{ zone2_limited_target }}°C, Heating={{ zone2_needs_heating }}

mode: queued
max: 10
